name: .NET

on:
  push:
    branches: [ mastur ]
    paths-ignore:
    - '**.md'
    - '_config.yml'
  pull_request:
    branches: [ mastur ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 5

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
    
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore LoveMachine.sln
 
    - name: Build and Publish
      run: msbuild LoveMachine.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
    - name: Upload Artifact
      if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.user.login != github.repository_owner) }}
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Published artifacts
        path: bin
